accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.Accounts.as_view(), name='accounts'),
    path('register/', views.Register.as_view(), name='register'),
    path('auth/<int:id>/<str:token>', views.Auth.as_view(), name='auth'),
    path('login/', views.Login.as_view(), name='login'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('delete/confirm/', views.Delete.as_view(), name='delete'),
    path('superuser/', views.Superuser.as_view(), name='superuser'),
    path('search/email/', views.Email.as_view(), name='email'),
    path('reset/password/', views.Password.as_view(), name='password'),
]

setup/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import user_passes_test
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

class Users(AbstractUser):
    username = models.CharField(max_length=255, unique=True, validators=[MinLengthValidator(8)])
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(_('active'), default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

accounts/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.views import generic, View
from django.contrib.auth import get_user_model, login as singin, logout as out, authenticate, views, mixins, hashers
from .form import AccountFormRegister, AccountFormLogin, AccountFormUpdate, AccountFormEmail, AccountFormConfirm, AccountFormResetPassword
from django.contrib import messages
from json import loads
from django.conf import settings
from django.forms.models import model_to_dict
from .utils import TokenEmailAndPassoerdResetGerator, enviar_email_html
from django.utils.html import format_html
from django.core.validators import ValidationError
from django.db.models import Q

User = get_user_model()
TOKEN = TokenEmailAndPassoerdResetGerator()

class Accounts(generic.ListView):
    model = User
    template_name = 'accounts.html'
    context_object_name = 'accounts'

    def get_queryset(self):
       return User.objects.all()

class Register(generic.CreateView):
    model = User
    form_class = AccountFormRegister
    template_name = 'register.html'

    def form_valid(self, form):
        if form.cleaned_data.get('password') != form.cleaned_data.get('passwordConfirm'):
            messages.error(self.request, 'As senhas não conhecidem.')
            return self.form_invalid(form)
        
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''
        for k, v in errors.items():
            for valor in v:
                if valor['code'] != 'unique':
                    erro_msg = valor['message']
                else:
                    erro_msg = f'Forneça um dado valido para o campo {k}'
        
        if erro_msg:
            messages.error(self.request, erro_msg)

        return super().form_invalid(form)


    def get_success_url(self):
        messages.warning(self.request, 'Conta criada com sucesso, mas precisa ser ativada, verifique seu e-mail.')
        return reverse('account:login')

class Auth(View):
    def get(self, request, id, token):
        try:
            account = get_object_or_404(User, pk=id)
            if not TOKEN.check_token(account, token):
                raise ValidationError('Token inválido.')
        except:
            return HttpResponse('Certifique-se de ter copiado a url corretamente.')
        else:
            account.is_active = True
            account.save()
            messages.success(request, 'Conta ativada')
            return redirect(reverse('account:login'))

        return redirect(reverse('account:accounts'))

class Login(generic.FormView):
    template_name = 'login.html'
    redirect_authenticated_user = True
    form_class = AccountFormLogin

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        singin(self.request, form.user)
        return super().form_valid(form)

    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''
        for k, v in errors.items():
            for valor in v:
                if valor['code'] != 'unique':
                    erro_msg = valor['message']
        
        if erro_msg:
            messages.error(self.request, erro_msg)

        return super().form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Login realizado com sucesso')
        return reverse('account:accounts')

class Profile(generic.UpdateView):
    model = User
    form_class = AccountFormUpdate
    template_name = 'update.html'

    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''

        for k, v in errors.items():
            for valor in v:
                if valor['code'] != 'unique':
                    erro_msg = valor['message']
        
        messages.error(self.request, erro_msg)
        return super().form_invalid(form)

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        messages.success(self.request, 'Cadastro atualizado com sucesso.')
        return reverse('account:profile')

class Logout(View):
    def get(self, request):
        out(request)
        messages.success(request, 'Sessão encerrada.')
        return redirect(reverse('account:accounts'))
        
class Delete(mixins.LoginRequiredMixin, generic.FormView):
    model = User
    form_class = AccountFormConfirm
    template_name = 'delete.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        account = self.request.user
        out(self.request)
        account.delete()
        messages.success(self.request, 'Conta excluída com sucesso.')
        return super().form_valid(form)

    def form_invalid(self, form):
        error = loads(form.errors.as_json())
        error = error.get('password')[0]['message']
        messages.error(self.request, error)
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('account:accounts')

class Superuser(View):
    def get(self, request):
        superuser = User.objects.filter(Q(is_staff=True) & Q(is_superuser=True))

        if not superuser:
            user = User.objects.create(username=settings.SUPERUSER_USERNAME, email=settings.SUPERUSER_EMAIL, password=hashers.make_password(settings.SUPERUSER_PASSWORD), is_staff=True, is_superuser=True, is_active=True)
            user.save()
            return HttpResponse(f"""<p>Superuser criado com sucesso. E-mail: {user.email} & password: {settings.SUPERUSER_PASSWORD}.
                                    <a href='{reverse('account:login')}'>Login aqui</a></p>""")
        else:
            return HttpResponse('Superusuário já criado.')

class Email(generic.FormView):
    model = User
    form_class = AccountFormEmail
    template_name = 'search_email.html'

    def form_valid(self, form):
        account = self.model.objects.get(email=form.cleaned_data.get('email'))
        token = TOKEN.make_token(account)
        url_absolute = settings.ABSOLUTE_URL + reverse('account:password') + f'?pk={account.id}&token={token}'
        link = format_html(f'<a href="{url_absolute}">Redefinir senha</a>')
        email = {
            'assunto': 'Redefinição de senha',
            'html': 'reset_password/email.html',
            'txt': 'reset_password/email.txt'
        }
        enviar_email_html(account, link, email)
        return HttpResponse('Enviamos o link de redefinição de conta, verifique seu e-mail.')

    def form_invalid(self, form):
        error = loads(form.errors.as_json())
        error = error.get('email')[0]['message']
        messages.error(self.request, error)
        return super().form_invalid(form)

class Password(generic.FormView):
    model = User
    template_name = 'reset_password.html'
    form_class = AccountFormResetPassword

    def get_initial(self):
        initial = super().get_initial()
        pk = self.request.GET.get('pk')
        token = self.request.GET.get('token')
        initial['pk'] = pk
        initial['token'] = token
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        password = form.cleaned_data.get('password')
        password = hashers.make_password(password)
        form.user.password = password
        form.user.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        errors = loads(form.errors.as_json())
        erro_msg = ''

        for k, v in errors.items():
            for valor in v:
                erro_msg = valor['message']
                break
        
        messages.error(self.request, erro_msg)
        return super().form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'Senha alterada com sucesso.')
        return redirect(reverse('account:login'))

accounts/templates/accounts.html
{% extends 'base.html' %}
{% block body %}
    <div class="flex items-center justify-between py-8 px-20">
        <h1 class="uppercase text-4xl font-bold">Sistema de cadastro</h1>
        <div class="flex gap-8 *:block *:py-2 *:px-4 *:no-underline *text-white *:rounded *:w-[10ch] *:text-center">
            {% if user.is_authenticated %}
                <a href="{% url 'account:profile' %}" class="bg-green-500 hover:bg-green-400">Perfil</a>
                <a href="{% url 'account:logout' %}" class="bg-zinc-500 hover:bg-zinc-400">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}" class="bg-green-500 hover:bg-green-400">Singin</a>
                <a href="{% url 'account:register' %}" class="bg-zinc-500 hover:bg-zinc-400">Singup</a>
            {% endif %}
        </div>
    </div>
    <div class="flex flex-col items-center">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="w-full max-w-lg flex justify-start">
            <h2 class="underline font-medium text-lg">Listagem de outros usuários:</h2>
        </div>
        <table class="w-full max-w-lg border-collapse mt-6 border p-2 text-left">
            <thead>
                <tr>
                    <th class="border p-2 text-left">Username</th>
                    <th class="border p-2 text-left">Nome</th>
                    <th class="border p-2 text-left">Sobrenome</th>
                    <th class="border p-2 text-left">Ultimo login</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                    <tr>
                        <td class="border p-2 text-left">{{account.username|capfirst}}</td>
                        <td class="border p-2 text-left">{{account.first_name|capfirst}}</td>
                        <td class="border p-2 text-left">{{account.last_name|capfirst}}</td>
                        <td class="border p-2 text-left">{% if account.last_login %} {{account.last_login|date:'d/m/Y'}} {% else %} sem dados {% endif %}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="border p-2 text-left">
                            Nenhum usuário encontrado.
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts/templates/delete.html
{% extends 'base.html' %}
{% block body %}
    <div class="flex flex-col justify-center items-center h-screen">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex flex-col items-center">
            <h1 class="uppercase text-center font-semibold text-lg underline">Confirmar</h1>
            <form action="{% url 'account:delete' %}" method="POST" class="p-4 bg-[#AAA] rounded-lg shadow-[0_0_5px_black] mt-8 w-[300px]">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col mt-2">
                        <label for="{{field.id_for_label}}" class="text-md font-semibold uppercase">{{field.label}}:</label>
                        {{field}}
                    </div>
                {% endfor %}
                <input type="submit" value="Confirmar" class="bg-black/90 hover:bg-black/75 text-[#f8cfcf] block w-full cursor-pointer mt-5 p-2 mt-3 rounded">
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% block body %}
    <div class="flex flex-col justify-center items-center h-screen">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex flex-col items-center">
            <h1 class="uppercase text-center font-semibold text-lg underline">Digite suas credencias</h1>
            <form action="{% url 'account:login' %}" method="POST" class="p-4 bg-[#AAA] rounded-lg shadow-[0_0_5px_black] mt-8 w-[300px]">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col mt-2">
                        <label for="{{field.id_for_label}}" class="text-md font-semibold uppercase">{{field.label}}:</label>
                        {{field}}
                    </div>
                {% endfor %}
                <div class="my-4">
                    <p class="text-base">Se deseja recuperar seu acesso. <a href="{% url 'account:email' %}" class="underline text-blue-700 hover:text-blue-500">Clique aqui.</a></p>
                </div>
                <input type="submit" value="Login" class="bg-black/90 hover:bg-black/75 text-[#f8cfcf] block w-full cursor-pointer mt-5 p-2 mt-3 rounded">
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block body %}
    <div class="flex flex-col justify-center items-center h-screen">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex flex-col items-center">
            <h1 class="uppercase text-center font-semibold text-lg underline">Formulario de cadastro</h1>
            <form action="{% url 'account:register' %}" method="POST" class="p-4 bg-[#AAA] rounded-lg shadow-[0_0_5px_black] mt-8 w-[300px]">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col mt-2">
                        {{field.label_tag}}
                        {{field}}
                    </div>
                {% endfor %}
                <div class="my-4">
                    <p class="text-base">Se deseja recuperar seu acesso. <a href="{% url 'account:email' %}" class="underline text-blue-700 hover:text-blue-500">Clique aqui.</a></p>
                </div>
                <input type="submit" value="Cadastrar" class="bg-black/90 hover:bg-black/75 text-[#f8cfcf] block w-full cursor-pointer mt-5 p-2 mt-3 rounded">
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/reset_password.html
{% extends 'base.html' %}
{% block body %}
    <div class="flex flex-col justify-center items-center h-screen">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex flex-col items-center">
            <h1 class="uppercase text-center font-semibold text-lg underline">Alterar senha</h1>
            <form action="{% url 'account:password' %}" method="POST" class="p-4 bg-[#AAA] rounded-lg shadow-[0_0_5px_black] mt-8 w-[300px]">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col mt-2">
                        <label for="{{field.id_for_label}}" class="text-md font-semibold uppercase">{{field.label}}:</label>
                        {{field}}
                    </div>
                {% endfor %}
                <input type="submit" value="Confirmar" class="bg-black/90 hover:bg-black/75 text-[#f8cfcf] block w-full cursor-pointer mt-5 p-2 mt-3 rounded">
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/search_email.html
{% extends 'base.html' %}
{% block body %}
    <div class="container_form">
        {% if messages %}
            {% for message in messages %}
                <div class="message_container {{message.tags}}">
                    <p  class="message_text">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="form_box">
            <h1 class="form_title">Encontrar conta</h1>
            <form action="{% url 'account:email' %}" method="POST" class="form_accounts">
                {% csrf_token %}
                {% for field in form %}
                    <div>
                        {{field.label_tag}}
                        {{field}}
                    </div>
                {% endfor %}
                <input type="submit" value="Buscar" class="form_submit">
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/update.html
{% extends 'base.html' %}
{% block body %}
    <p class="text-lg">Deletar conta. <a href="{% url 'account:delete' %}" class="underline text-blue-700 hover:text-blue-500">click aqui.</a></p>
    <div class="flex flex-col justify-center items-center h-screen">
        {% if messages %}
            {% for message in messages %}
                <div class="absolute top-4 py-4 px-8 mx-auto border-2 {{message.tags}}">
                    <p  class="text-xl">{{message}}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div class="flex flex-col items-center">
            <h1 class="uppercase text-center font-semibold text-lg underline">Dados do usuário</h1>
            <form action="{% url 'account:profile' %}" method="POST" class="p-4 bg-[#AAA] rounded-lg shadow-[0_0_5px_black] mt-8 w-[300px]">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col mt-2">
                        <label for="{{field.id_for_label}}" class="text-md font-semibold uppercase">{{field.label}}:</label>
                        {{field}}
                    </div>
                {% endfor %}
                <div class="my-4">
                    <p class="text-base">Se deseja alterar sua senha. <a href="{% url 'account:password' %}" class="underline text-blue-700 hover:text-blue-500">Clique aqui.</a></p>
                </div>
                <input type="submit" value="Atualizar" class="bg-black/90 hover:bg-black/75 text-[#f8cfcf] block w-full cursor-pointer mt-5 p-2 mt-3 rounded">
            </form>
        </div>
    </div>
{% endblock %}